version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: langgraph-platform
          ContainerPort: 3000
        PlatformVersion: LATEST
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - <SUBNET_1>
              - <SUBNET_2>
            SecurityGroups:
              - <SECURITY_GROUP>
            AssignPublicIp: DISABLED

Hooks:
  - BeforeInstall: "BeforeInstall"
  - AfterInstall: "AfterInstall"
  - AfterAllowTestTraffic: "AfterAllowTestTraffic"
  - BeforeAllowTraffic: "BeforeAllowTraffic"
  - AfterAllowTraffic: "AfterAllowTraffic"
